name = "hex-number-field-tower-mathlib"
defaultTargets = ["HexNumberFieldTowerMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexNumberFieldTower"
git = "https://github.com/leanprover/hex-number-field-tower.git"
rev = "v0.2.0"

[[require]]
name = "HexNumberFieldMathlib"
git = "https://github.com/leanprover/hex-number-field-mathlib.git"
rev = "v0.2.0"

[[require]]
name = "HexResultantMathlib"
git = "https://github.com/leanprover/hex-resultant-mathlib.git"
rev = "v0.2.0"

[[require]]
name = "HexBerlekampZassenhausMathlib"
git = "https://github.com/leanprover/hex-berlekamp-zassenhaus-mathlib.git"
rev = "v0.2.0"

[[require]]
name = "HexRowReduceMathlib"
git = "https://github.com/leanprover/hex-row-reduce-mathlib.git"
rev = "v0.2.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexNumberFieldTowerMathlib"
