name = "hex-number-field-tower-mathlib"
defaultTargets = ["HexNumberFieldTowerMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexNumberFieldTower"
git = "https://github.com/leanprover/hex-number-field-tower.git"
rev = "98e91f4d44afa362edf95878b0795bed0928e6a8"

[[require]]
name = "HexNumberFieldMathlib"
git = "https://github.com/leanprover/hex-number-field-mathlib.git"
rev = "8197b38919eb8e76248c2e9b28d37cd96f6007c4"

[[require]]
name = "HexResultantMathlib"
git = "https://github.com/leanprover/hex-resultant-mathlib.git"
rev = "b40bef9d6083c1df635867813fac6c3bc8455a4e"

[[require]]
name = "HexBerlekampZassenhausMathlib"
git = "https://github.com/leanprover/hex-berlekamp-zassenhaus-mathlib.git"
rev = "a64dd3e6c11d864be268121845c9705eb230b1fe"

[[require]]
name = "HexRowReduceMathlib"
git = "https://github.com/leanprover/hex-row-reduce-mathlib.git"
rev = "5b0b760e455c2a5e0bd1811803598075c2e81a0b"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexNumberFieldTowerMathlib"
