/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexNumberFieldTowerMathlib.Factor

public section

/-!
# Correctness of checked root adjoining

An {name}`Hex.NumberTower.Extension` is a dependent runtime payload and its
constructor is public, so semantic validity is an explicit predicate proved
for {name}`Hex.NumberTower.adjoin?` results.
-/

namespace Hex.NumberTower

namespace Evaluation

/-- Successful executable evaluation of tower coordinates preserves their
fixed complex value. -/
theorem evalElem?_sound (T : NumberTower) (a : Elem T)
    {root : AlgebraicRoot} (h : evalElem? T a = some root) :
    root.toComplex = T.toComplex a := by
  exact (toComplex_eq T a h).symm

/-- Coordinate evaluation succeeds for every validated tower element. -/
theorem evalElem?_isSome (T : NumberTower) (a : Elem T) :
    (evalElem? T a).isSome := by
  simpa [NumberTower.eval?, evalElem?] using eval?_isSome T a

/-- Successful exact tower-polynomial evaluation agrees with semantic
polynomial evaluation. -/
theorem evalPoly?_sound (T : NumberTower) (f : Poly T)
    (candidate result : AlgebraicRoot)
    (h : evalPoly? T f candidate = some result) :
    result.toComplex =
      Polynomial.eval candidate.toComplex (T.toPolynomial f) := by
  rw [toPolynomial_eq_polynomial]
  exact LevelSemantics.evalPoly_sound T.levels.toList
    (f.toArray.map coeffs) candidate result h

/-- The bounded zero test returns a Boolean for every public tower
polynomial. -/
theorem vanishesAt?_isSome (T : NumberTower) (f : Poly T)
    (candidate : AlgebraicRoot) :
    (vanishesAt? T f candidate).isSome := by
  exact rawVanishesAt_isSome T.levels.toList (f.toArray.map coeffs)
    candidate (polyCoords_rawPoly T f)

/-- The total public zero test returns `true` exactly at a semantic root. -/
theorem vanishesAt?_eq_some_true_iff (T : NumberTower) (f : Poly T)
    (candidate : AlgebraicRoot) :
    vanishesAt? T f candidate = some true ↔
      Polynomial.eval candidate.toComplex (T.toPolynomial f) = 0 := by
  constructor
  · intro h
    rw [toPolynomial_eq_polynomial]
    exact (rawVanishesAt_sound T.levels.toList
      (f.toArray.map coeffs) candidate h).mp rfl
  · intro hzero
    obtain ⟨keep, hkeep⟩ := Option.isSome_iff_exists.mp
      (vanishesAt?_isSome T f candidate)
    have hcorrect := rawVanishesAt_sound T.levels.toList
      (f.toArray.map coeffs) candidate hkeep
    rw [toPolynomial_eq_polynomial] at hzero
    have : keep = true := by simpa using hcorrect.mpr hzero
    simpa [this] using hkeep

end Evaluation

namespace Extension

/-- Evaluate a base-tower polynomial at an extension element after embedding
its coefficients. -/
@[expose]
def evalPoly {T : NumberTower} (E : Extension T)
    (f : Poly T) (a : Elem E.tower) : Elem E.tower :=
  f.toArray.foldr
    (fun coefficient value => E.embed coefficient + a * value) 0

/-- Every element of the result is generated by the old tower and the
distinguished generator. -/
@[expose]
def Generated {T : NumberTower} (E : Extension T) : Prop :=
  ∀ b : Elem E.tower, ∃ f : Poly T, E.evalPoly f E.gen = b

/-- The candidate value was already present in the old fixed embedding. -/
@[expose]
def AlreadyContains (T : NumberTower) (candidate : AlgebraicRoot) : Prop :=
  ∃ a : Elem T, T.toComplex a = candidate.toComplex

/-- Mathematical meaning of a checked adjoining result. -/
@[expose]
def Sound {T : NumberTower} (candidate : AlgebraicRoot)
    (E : Extension T) : Prop :=
  E.PreservesEmbedding ∧
    E.GeneratorValue ∧
    E.root.toComplex = candidate.toComplex ∧
    E.Generated ∧
    (E.tower.dim = T.dim ↔ AlreadyContains T candidate)

end Extension

/-- Lifting an integer polynomial into a tower preserves its complex
coefficient polynomial. -/
theorem toPolynomial_liftZPoly (T : NumberTower) (p : ZPoly) :
    T.toPolynomial (liftZPoly T p) = HexRootsMathlib.toPolyℂ p := by
  ext n
  rw [coeff_toPolynomial]
  simp only [liftZPoly, DensePoly.coeff_ofCoeffs, HexRootsMathlib.toPolyℂ,
    Polynomial.coeff_map, HexPolyMathlib.coeff_toPolynomial]
  by_cases h : n < p.size
  · simp [Array.getD, h, toComplex_ofRat,
      ← DensePoly.toArray_getD p n]
  · simp only [Array.getD, Array.size_map, DensePoly.toArray_size, h,
      ↓reduceDIte, DensePoly.coeff_eq_zero_of_size_le p
        (Nat.le_of_not_gt h)]
    calc
      T.toComplex (0 : Elem T) = T.toComplex (T.ofRat 0) :=
        congrArg T.toComplex (zero_eq_ofRat T)
      _ = (0 : ℂ) := by simpa using toComplex_ofRat T 0
      _ = (Int.castRingHom ℂ) (0 : Int) := by norm_num

open scoped TowerField

private theorem liftZPoly_separable (T : NumberTower)
    (candidate : AlgebraicRoot) :
    (HexPolyMathlib.toPolynomial (liftZPoly T candidate.p)).Separable := by
  have hpne : candidate.p ≠ 0 := by
    intro hp
    have hdegree := candidate.pos_degree
    rw [hp] at hdegree
    simp at hdegree
  have hcomplex : (HexRootsMathlib.toPolyℂ candidate.p).Separable := by
    have hmapped :=
      (HexRootsMathlib.HasOnlySimpleRoots.separable candidate.squarefree hpne).map
        (f := algebraMap Rat ℂ)
    have hcomp :
        (algebraMap Rat ℂ).comp (Int.castRingHom Rat) =
          Int.castRingHom ℂ := RingHom.ext_int _ _
    simpa [HexPolyZMathlib.toPolyℚ, HexRootsMathlib.toPolyℂ,
      Polynomial.map_map, hcomp] using hmapped
  have hmapped :
      (HexPolyMathlib.toPolynomial (liftZPoly T candidate.p)).map
          T.embedding = HexRootsMathlib.toPolyℂ candidate.p := by
    rw [← toPolynomial_eq_map, toPolynomial_liftZPoly]
  apply (Polynomial.separable_map T.embedding).mp
  rwa [hmapped]

private theorem factorPower_dvd_reconstruct {T : NumberTower} {f : Poly T}
    (r : Factorization T f) (entry : Poly T × Nat)
    (hentry : entry ∈ r.factors.toList) :
    HexPolyMathlib.toPolynomial entry.1 ^ entry.2 ∣
      HexPolyMathlib.toPolynomial r.reconstruct := by
  have hmem : HexPolyMathlib.toPolynomial entry.1 ^ entry.2 ∈
      r.factors.toList.map fun factor =>
        HexPolyMathlib.toPolynomial factor.1 ^ factor.2 := by
    exact List.mem_map.mpr ⟨entry, hentry, rfl⟩
  obtain ⟨q, hq⟩ := List.dvd_prod hmem
  refine ⟨Polynomial.C r.scalar * q, ?_⟩
  rw [toPolynomial_reconstruct, hq]
  ac_rfl

private theorem factor_multiplicity_one {T : NumberTower} {f : Poly T}
    (r : Factorization T f) (hsound : r.Sound)
    (hseparable : (HexPolyMathlib.toPolynomial f).Separable)
    (entry : Poly T × Nat) (hentry : entry ∈ r.factors.toList) :
    entry.2 = 1 := by
  have hentrySound := hsound.2.1 entry hentry
  have hpowSeparable :
      (HexPolyMathlib.toPolynomial entry.1 ^ entry.2).Separable := by
    apply hseparable.of_dvd
    rw [← hsound.1]
    exact factorPower_dvd_reconstruct r entry hentry
  have hirreducible :
      Irreducible (HexPolyMathlib.toPolynomial entry.1) :=
    (polynomialIrreducible_iff T entry.1).mp hentrySound.2.2
  exact (hpowSeparable.of_pow hirreducible.not_isUnit
    (Nat.ne_of_gt hentrySound.2.1)).2

private theorem exists_vanishing_factor (T : NumberTower)
    (candidate : AlgebraicRoot)
    (r : Factorization T (liftZPoly T candidate.p))
    (hsound : r.Sound) :
    ∃ entry ∈ r.factors.toList,
      Polynomial.eval candidate.toComplex (T.toPolynomial entry.1) = 0 := by
  have hroot : Polynomial.eval candidate.toComplex
      (T.toPolynomial (liftZPoly T candidate.p)) = 0 := by
    rw [toPolynomial_liftZPoly]
    exact AlgebraicRoot.toComplex_isRoot candidate
  have hscalar : T.toComplex r.scalar ≠ 0 := by
    intro hzero
    have hreconstruct : T.toPolynomial r.reconstruct = 0 := by
      rw [semantic_reconstruct, hzero]
      simp
    have hinput : T.toPolynomial (liftZPoly T candidate.p) = 0 := by
      rw [← hsound.1]
      exact hreconstruct
    have hpne := HexRootsMathlib.RefinedIsolation.poly_ne_zero candidate.rep
    have hsize : candidate.p.size ≠ 0 := by
      intro hsize
      exact hpne ((DensePoly.size_eq_zero_iff candidate.p).mp hsize)
    exact HexRootsMathlib.toPolyℂ_ne_zero candidate.p hsize <|
      (toPolynomial_liftZPoly T candidate.p).symm.trans hinput
  have hproduct : Polynomial.eval candidate.toComplex
      ((r.factors.toList.map fun factor =>
        T.toPolynomial factor.1 ^ factor.2).prod) = 0 := by
    have hreconstruct : Polynomial.eval candidate.toComplex
        (T.toPolynomial r.reconstruct) = 0 := by
      rw [hsound.1]
      exact hroot
    rw [semantic_reconstruct, Polynomial.eval_mul, Polynomial.eval_C]
      at hreconstruct
    exact (mul_eq_zero.mp hreconstruct).resolve_left hscalar
  rw [Polynomial.eval_list_prod] at hproduct
  simp only [List.map_map, List.prod_eq_zero_iff] at hproduct
  obtain ⟨entry, hentry, hpow⟩ := List.mem_map.mp hproduct
  unfold Function.comp at hpow
  rw [Polynomial.eval_pow] at hpow
  exact ⟨entry, hentry, eq_zero_of_pow_eq_zero hpow⟩

private theorem ratListLess_self : ∀ values : List Rat,
    Factor.ratListLess values values = false
  | [] => by simp [Factor.ratListLess]
  | value :: values => by
      simp [Factor.ratListLess, lt_irrefl value, ratListLess_self values]

private theorem factorLess_self (f : Array (Array Rat)) :
    Factor.factorLess f f = false := by
  simp [Factor.factorLess, ratListLess_self]

/-- Strict canonical factor ordering makes the public factor polynomials
pairwise distinct. -/
theorem factor_fsts_pairwise {T : NumberTower} {f : Poly T}
    (r : Factorization T f) (hsound : r.Sound) :
    r.factors.toList.Pairwise fun a b => a.1 ≠ b.1 := by
  have hsorted := hsound.2.2
  simp only [Factor.factorsSorted, decide_eq_true_eq] at hsorted
  have hpublic : r.factors.toList.Pairwise fun a b =>
      Factor.factorLess (a.1.toArray.map coeffs)
        (b.1.toArray.map coeffs) = true := by
    rw [Array.toList_map, List.pairwise_map] at hsorted
    exact hsorted
  apply hpublic.imp
  intro a b hab heq
  rw [heq, factorLess_self] at hab
  contradiction

private theorem vanishing_factor_unique {T : NumberTower} {f : Poly T}
    (r : Factorization T f) (hsound : r.Sound)
    (candidate : AlgebraicRoot)
    (a b : Poly T × Nat) (ha : a ∈ r.factors.toList)
    (hb : b ∈ r.factors.toList)
    (hza : Polynomial.eval candidate.toComplex
      (T.toPolynomial a.1) = 0)
    (hzb : Polynomial.eval candidate.toComplex
      (T.toPolynomial b.1) = 0) :
    a = b := by
  by_contra hab
  letI : Std.Symm (fun x y : Poly T × Nat => x.1 ≠ y.1) :=
    ⟨fun _ _ h => h.symm⟩
  have hfactorNe : a.1 ≠ b.1 :=
    (factor_fsts_pairwise r hsound).forall ha hb hab
  have haSound := hsound.2.1 a ha
  have hbSound := hsound.2.1 b hb
  have hpMonic : (HexPolyMathlib.toPolynomial a.1).Monic := by
    rw [Polynomial.Monic.def,
      HexPolyMathlib.leadingCoeff_toPolynomial, haSound.1]
  have hqMonic : (HexPolyMathlib.toPolynomial b.1).Monic := by
    rw [Polynomial.Monic.def,
      HexPolyMathlib.leadingCoeff_toPolynomial, hbSound.1]
  have hpIrreducible :
      Irreducible (HexPolyMathlib.toPolynomial a.1) :=
    (polynomialIrreducible_iff T a.1).mp haSound.2.2
  have hqIrreducible :
      Irreducible (HexPolyMathlib.toPolynomial b.1) :=
    (polynomialIrreducible_iff T b.1).mp hbSound.2.2
  have hnotAssociated : ¬Associated
      (HexPolyMathlib.toPolynomial a.1)
      (HexPolyMathlib.toPolynomial b.1) := by
    intro hassociated
    have hpq := Polynomial.eq_of_monic_of_associated
      hpMonic hqMonic hassociated
    exact hfactorNe (HexPolyMathlib.equiv.injective hpq)
  have hcoprime : IsCoprime
      (HexPolyMathlib.toPolynomial a.1)
      (HexPolyMathlib.toPolynomial b.1) := by
    rcases dvd_or_isCoprime (HexPolyMathlib.toPolynomial a.1)
        (HexPolyMathlib.toPolynomial b.1) hpIrreducible with
      hdvd | hcoprime
    · exact (hnotAssociated
        (hpIrreducible.associated_of_dvd hqIrreducible hdvd)).elim
    · exact hcoprime
  have hmapped := hcoprime.map (Polynomial.mapRingHom T.embedding)
  have hevaluated := hmapped.map
    (Polynomial.evalRingHom candidate.toComplex)
  have hza' : Polynomial.eval candidate.toComplex
      ((HexPolyMathlib.toPolynomial a.1).map T.embedding) = 0 := by
    rw [← toPolynomial_eq_map]
    exact hza
  have hzb' : Polynomial.eval candidate.toComplex
      ((HexPolyMathlib.toPolynomial b.1).map T.embedding) = 0 := by
    rw [← toPolynomial_eq_map]
    exact hzb
  change IsCoprime
      (Polynomial.eval candidate.toComplex
        ((HexPolyMathlib.toPolynomial a.1).map T.embedding))
      (Polynomial.eval candidate.toComplex
        ((HexPolyMathlib.toPolynomial b.1).map T.embedding)) at hevaluated
  rw [hza', hzb'] at hevaluated
  exact not_isCoprime_zero_zero hevaluated

private theorem selectFold_no_match (T : NumberTower)
    (candidate : AlgebraicRoot) :
    ∀ (items : List (Poly T × Nat)) (state : Array (Poly T)),
      (∀ entry ∈ items, entry.2 = 1) →
      (∀ entry ∈ items,
        Evaluation.vanishesAt? T entry.1 candidate = some false) →
      items.foldlM (fun selected entry => do
        if entry.2 = 1 then
          let keep ← Evaluation.vanishesAt? T entry.1 candidate
          if keep then some (selected.push entry.1) else some selected
        else
          none) state = some state
  | [], state, _, _ => by simp
  | entry :: items, state, hmult, hfalse => by
      rw [List.foldlM_cons]
      have hmultHead := hmult entry (by simp)
      have hfalseHead := hfalse entry (by simp)
      simp only [hmultHead, ↓reduceIte, hfalseHead, Option.bind_some,
        Bool.false_eq_true, ↓reduceIte]
      apply selectFold_no_match T candidate items state
      · intro other hother
        exact hmult other (by simp [hother])
      · intro other hother
        exact hfalse other (by simp [hother])

private theorem selectFold_unique (T : NumberTower)
    (candidate : AlgebraicRoot) (chosen : Poly T × Nat) :
    ∀ (items : List (Poly T × Nat)) (state : Array (Poly T)),
      items.Nodup → chosen ∈ items →
      (∀ entry ∈ items, entry.2 = 1) →
      Evaluation.vanishesAt? T chosen.1 candidate = some true →
      (∀ entry ∈ items, entry ≠ chosen →
        Evaluation.vanishesAt? T entry.1 candidate = some false) →
      items.foldlM (fun selected entry => do
        if entry.2 = 1 then
          let keep ← Evaluation.vanishesAt? T entry.1 candidate
          if keep then some (selected.push entry.1) else some selected
        else
          none) state = some (state.push chosen.1)
  | [], _, _, hchosen, _, _, _ => by simp at hchosen
  | entry :: items, state, hnodup, hchosen, hmult, htrue, hfalse => by
      rw [List.foldlM_cons]
      have hmultHead := hmult entry (by simp)
      rcases List.nodup_cons.mp hnodup with ⟨hheadFresh, htailNodup⟩
      rcases List.mem_cons.mp hchosen with rfl | hchosenTail
      · simp only [hmultHead, ↓reduceIte, htrue, Option.bind_some,
          ↓reduceIte]
        apply selectFold_no_match T candidate items (state.push chosen.1)
        · intro other hother
          exact hmult other (by simp [hother])
        · intro other hother
          apply hfalse other (by simp [hother])
          intro heq
          subst other
          exact hheadFresh hother
      · have hentryNe : entry ≠ chosen := by
          intro heq
          subst entry
          exact hheadFresh hchosenTail
        have hfalseHead := hfalse entry (by simp) hentryNe
        simp only [hmultHead, ↓reduceIte, hfalseHead, Option.bind_some,
          Bool.false_eq_true, ↓reduceIte]
        apply selectFold_unique T candidate chosen items state htailNodup
          hchosenTail
        · intro other hother
          exact hmult other (by simp [hother])
        · exact htrue
        · intro other hother hne
          exact hfalse other (by simp [hother]) hne

private theorem selectFactor?_complete (T : NumberTower)
    (candidate : AlgebraicRoot) (factors : Array (Poly T × Nat))
    (chosen : Poly T × Nat)
    (hnodup : factors.toList.Nodup) (hchosen : chosen ∈ factors.toList)
    (hmult : ∀ entry ∈ factors.toList, entry.2 = 1)
    (htrue : Evaluation.vanishesAt? T chosen.1 candidate = some true)
    (hfalse : ∀ entry ∈ factors.toList, entry ≠ chosen →
      Evaluation.vanishesAt? T entry.1 candidate = some false) :
    selectFactor? T candidate factors = some chosen.1 := by
  have hfold := selectFold_unique T candidate chosen factors.toList #[]
    hnodup hchosen hmult htrue hfalse
  unfold selectFactor?
  rw [← Array.foldlM_toList, hfold]
  simp

private theorem levelOfFactor_polynomial (T : NumberTower)
    (candidate : AlgebraicRoot) (selected : Poly T)
    (hmonic : selected.leadingCoeff = 1)
    (hdegree : 0 < selected.degree?.getD 0) :
    (levelOfFactor candidate selected).polynomial T.levels.toList =
      selected.toArray.map coeffs := by
  let d := selected.degree?.getD 0
  have hsizePos : 0 < selected.size := by
    by_contra hnot
    have hsize : selected.size = 0 := Nat.eq_zero_of_not_pos hnot
    rw [DensePoly.degree?_eq_none_iff selected |>.mpr hsize] at hdegree
    simp at hdegree
  have hd : selected.size - 1 = d := by
    change selected.size - 1 = selected.degree?.getD 0
    rw [DensePoly.degree?_eq_some_of_pos_size selected hsizePos,
      Option.getD_some]
  have hsize : selected.size = d + 1 := by omega
  apply Array.ext
  · simp [Level.polynomial, levelOfFactor, d, hsize]
  · intro i hi₁ hi₂
    have hi : i < d + 1 := by simpa [Level.polynomial, levelOfFactor, d]
      using hi₁
    by_cases hid : i < d
    · have hiSelected : i < selected.size := by omega
      simp [Level.polynomial, levelOfFactor, d, hid]
      apply congrArg coeffs
      have hgetD := DensePoly.toArray_getD selected i
      simpa [Array.getD, hiSelected] using hgetD.symm
    · have hieq : i = d := by omega
      subst i
      have hdArray : d < selected.toArray.size := by simp [hsize]
      have htop : selected.toArray[d] = selected.leadingCoeff := by
        have hgetD := DensePoly.toArray_getD selected d
        have hdSelected : d < selected.size := by simpa using hdArray
        rw [DensePoly.leadingCoeff_eq_coeff_last selected (by omega), hsize]
        simpa [Array.getD, hdSelected] using hgetD
      rw [Array.getElem_map, htop, hmonic]
      simp [Level.polynomial, levelOfFactor, d, Arithmetic.fixedCoeffs,
        coeffs, one_eq_ofRat, ofRat_eq_ofCoeffs]
      change _ = coeffs (T.ofCoeffs #[1])
      rw [coeffs_ofCoeffs]
      rw [normalizeCoeffs]
      rw [Vector.toArray_ofFn]
      apply Array.ext
      · simp [dim]
      · intro i hi₃ hi₄
        rcases i with _ | i
        · simp [Array.getD]
        · simp [Array.getD]

private theorem levelOfFactor_structuralCheck (T : NumberTower)
    (candidate : AlgebraicRoot) (selected : Poly T)
    (hdegree : 1 < selected.degree?.getD 0) :
    (levelOfFactor candidate selected).structuralCheck T.dim = true := by
  simp only [Level.structuralCheck, Bool.and_eq_true, decide_eq_true_eq]
  refine ⟨⟨by simpa [levelOfFactor] using hdegree, by
    simp [levelOfFactor]⟩, ?_⟩
  rw [Array.all_eq_true]
  intro i hi
  simp [levelOfFactor, coeffs_size]

private theorem extend_factor_isSome (T : NumberTower)
    (candidate : AlgebraicRoot) (selected : Poly T)
    (hmonic : selected.leadingCoeff = 1)
    (hirreducible : PolynomialIrreducible T selected)
    (hvanish : Polynomial.eval candidate.toComplex
      (T.toPolynomial selected) = 0)
    (hdegree : 1 < selected.degree?.getD 0) :
    (Internal.extend? T (levelOfFactor candidate selected)).isSome := by
  have hdegreePos : 0 < selected.degree?.getD 0 := by omega
  have hpolynomial := levelOfFactor_polynomial T candidate selected
    hmonic hdegreePos
  have hstruct := levelOfFactor_structuralCheck T candidate selected
    hdegree
  have hirred : Factor.isIrreducible T.levels.toList
      ((levelOfFactor candidate selected).polynomial T.levels.toList) =
        true := by
    rw [hpolynomial]
    exact (isIrreducible_iff T selected).mpr ⟨hmonic, hirreducible⟩
  have hembed : RawEvaluation.vanishesAt? T.levels.toList
      ((levelOfFactor candidate selected).polynomial T.levels.toList)
      candidate = some true := by
    rw [hpolynomial]
    exact (Evaluation.vanishesAt?_eq_some_true_iff
      T selected candidate).mpr hvanish
  exact Internal.extend?_isSome T (levelOfFactor candidate selected)
    (by simpa [levelOfFactor] using hdegree) hstruct hirred hembed

private theorem selectFold_mem (T : NumberTower)
    (candidate : AlgebraicRoot) (items : List (Poly T × Nat))
    (state out : Array (Poly T))
    (hrun : items.foldlM (fun selected entry => do
      if entry.2 = 1 then
        let keep ← Evaluation.vanishesAt? T entry.1 candidate
        if keep then some (selected.push entry.1) else some selected
      else
        none) state = some out) {p : Poly T} (hp : p ∈ out.toList) :
    p ∈ state.toList ∨
      ∃ entry ∈ items, entry.1 = p ∧
        entry.2 = 1 ∧
        Evaluation.vanishesAt? T entry.1 candidate = some true := by
  induction items generalizing state with
  | nil =>
      simp only [List.foldlM_nil, Option.pure_def, Option.some.injEq] at hrun
      subst out
      exact Or.inl hp
  | cons entry items ih =>
      rw [List.foldlM_cons] at hrun
      by_cases hmult : entry.2 = 1
      · cases hvanish : Evaluation.vanishesAt? T entry.1 candidate with
        | none => simp [hmult, hvanish] at hrun
        | some keep =>
            cases keep with
            | false =>
                have htail : items.foldlM (fun selected entry => do
                    if entry.2 = 1 then
                      let keep ← Evaluation.vanishesAt? T entry.1 candidate
                      if keep then some (selected.push entry.1)
                      else some selected
                    else none) state = some out := by
                  simpa [hmult, hvanish] using hrun
                rcases ih state htail with hstate | ⟨found, hfound, rfl, hzero⟩
                · exact Or.inl hstate
                · exact Or.inr ⟨found, by simp [hfound], rfl, hzero⟩
            | true =>
                have htail : items.foldlM (fun selected entry => do
                    if entry.2 = 1 then
                      let keep ← Evaluation.vanishesAt? T entry.1 candidate
                      if keep then some (selected.push entry.1)
                      else some selected
                    else none) (state.push entry.1) = some out := by
                  simpa [hmult, hvanish] using hrun
                rcases ih (state.push entry.1) htail with
                  hstate | ⟨found, hfound, rfl, hzero⟩
                · simp only [Array.toList_push, List.mem_append,
                    List.mem_singleton] at hstate
                  rcases hstate with hstate | rfl
                  · exact Or.inl hstate
                  · exact Or.inr ⟨entry, by simp, rfl, hmult, hvanish⟩
                · exact Or.inr ⟨found, by simp [hfound], rfl, hzero⟩
      · simp [hmult] at hrun

private theorem selectFactor?_source (T : NumberTower)
    (candidate : AlgebraicRoot) (factors : Array (Poly T × Nat))
    {selected : Poly T} (h : selectFactor? T candidate factors = some selected) :
    ∃ entry ∈ factors.toList, entry.1 = selected ∧ entry.2 = 1 ∧
      Evaluation.vanishesAt? T entry.1 candidate = some true := by
  unfold selectFactor? at h
  obtain ⟨retained, hfold, hmatch⟩ := Option.bind_eq_some_iff.mp h
  cases hretained : retained.toList with
  | nil => simp [hretained] at hmatch
  | cons factor tail =>
      cases tail with
      | nil =>
          have hselected : factor = selected := by
            simpa [hretained] using hmatch
          subst selected
          have hfoldList := hfold
          rw [← Array.foldlM_toList] at hfoldList
          have hmember : factor ∈ retained.toList := by
            simp [hretained]
          rcases selectFold_mem T candidate factors.toList #[] retained
              hfoldList hmember with himpossible | hsource
          · simp at himpossible
          · exact hsource
      | cons next rest => simp [hretained] at hmatch

/-- A selected relative factor is irreducible and vanishes at the requested
absolute candidate under the fixed embedding. -/
theorem selectFactor?_sound (T : NumberTower) (candidate : AlgebraicRoot)
    (factors : Array (Poly T × Nat)) {selected : Poly T}
    (hirreducible : ∀ entry ∈ factors.toList,
      PolynomialIrreducible T entry.1)
    (h : selectFactor? T candidate factors = some selected) :
    PolynomialIrreducible T selected ∧
      Polynomial.eval candidate.toComplex (T.toPolynomial selected) = 0 := by
  obtain ⟨entry, hentry, rfl, _hmult, hvanish⟩ :=
    selectFactor?_source T candidate factors h
  refine ⟨hirreducible entry hentry, ?_⟩
  rw [toPolynomial_eq_polynomial]
  exact (rawVanishesAt_sound
    T.levels.toList (entry.1.toArray.map coeffs)
    candidate hvanish).mp rfl

/-- Horner evaluation in a checked extension agrees with ordinary semantic
evaluation at its distinguished root. -/
theorem Extension.toComplex_evalPoly {T : NumberTower} (E : Extension T)
    (hpreserves : E.PreservesEmbedding) (hgenerator : E.GeneratorValue)
    (f : Poly T) :
    E.tower.toComplex (E.evalPoly f E.gen) =
      Polynomial.eval E.root.toComplex (T.toPolynomial f) := by
  unfold Extension.evalPoly toPolynomial
  rw [← Array.foldr_toList, ← Array.foldr_toList]
  generalize f.toArray.toList = coefficients
  induction coefficients with
  | nil => simp [map_zero]
  | cons coefficient coefficients ih =>
      simp only [List.foldr_cons, Polynomial.eval_add,
        Polynomial.eval_C, Polynomial.eval_mul, Polynomial.eval_X]
      rw [map_add, map_mul, hpreserves coefficient, hgenerator, ih]

private theorem extend_preserves (T tower : NumberTower) (level : Level)
    (htower : Internal.extend? T level = some tower) :
    ∀ a : Elem T,
      tower.toComplex (tower.ofCoeffs (coeffs a)) = T.toComplex a := by
  intro a
  have hlevels := Internal.extend?_levels T level htower
  have hvalid : LevelsValid (level :: T.levels.toList) := by
    rw [← hlevels]
    exact tower.valid
  rw [LevelSemantics.toComplex_eq_denote, coeffs_ofCoeffs]
  change LevelSemantics.denote tower.levels.toList
      (Arithmetic.fixedCoeffs (levelsDim tower.levels.toList) (coeffs a)) = _
  rw [LevelSemantics.denote_fixed,
    hlevels]
  rw [LevelSemantics.denote_embed level T.levels.toList hvalid (coeffs a)
    (by simp [dim])]
  exact (LevelSemantics.toComplex_eq_denote T a).symm

private theorem extend_generator (T tower : NumberTower) (level : Level)
    (htower : Internal.extend? T level = some tower)
    (hdegree : 1 < level.degree) :
    tower.toComplex
        (tower.ofCoeffs ((Array.replicate T.dim 0).push 1)) =
      level.root.toComplex := by
  have hlevels := Internal.extend?_levels T level htower
  have hvalid : LevelsValid (level :: T.levels.toList) := by
    rw [← hlevels]
    exact tower.valid
  rw [LevelSemantics.toComplex_eq_denote, coeffs_ofCoeffs]
  change LevelSemantics.denote tower.levels.toList
      (Arithmetic.fixedCoeffs (levelsDim tower.levels.toList)
        ((Array.replicate T.dim 0).push 1)) = _
  rw [LevelSemantics.denote_fixed,
    hlevels]
  exact LevelSemantics.denote_generator level T.levels.toList
    hvalid hdegree

/-- Read the top-level coefficient blocks of an extended element as a
polynomial over the lower tower. -/
private def blockPoly (T : NumberTower) (level : Level)
    {tower : NumberTower} (b : Elem tower) : Poly T :=
  DensePoly.ofCoeffs <| ((List.range level.degree).map fun i =>
    T.ofCoeffs (Arithmetic.block (coeffs b) i T.dim)).toArray

private theorem degree?_lt_of_size_le {T : NumberTower} (f : Poly T)
    {bound : Nat} (hbound : 0 < bound) (hsize : f.size ≤ bound) :
    f.degree?.getD 0 < bound := by
  by_cases hzero : f.size = 0
  · rw [DensePoly.degree?_eq_none_iff f |>.mpr hzero]
    simpa using hbound
  · rw [DensePoly.degree?_eq_some_of_pos_size f
      (Nat.zero_lt_of_ne_zero hzero), Option.getD_some]
    omega

private theorem eval_blockPoly (T tower : NumberTower) (level : Level)
    (htower : Internal.extend? T level = some tower)
    (hdegree : 0 < level.degree) (b : Elem tower) :
    Polynomial.eval level.root.toComplex
        (T.toPolynomial (blockPoly T level b)) =
      tower.toComplex b := by
  have hlevels := Internal.extend?_levels T level htower
  have hpolyDegree :
      (T.toPolynomial (blockPoly T level b)).natDegree < level.degree := by
    rw [natDegree_toPolynomial]
    apply degree?_lt_of_size_le (blockPoly T level b) hdegree
    exact (DensePoly.size_ofCoeffs_le _).trans (by simp)
  rw [Polynomial.eval_eq_sum_range' hpolyDegree]
  rw [LevelSemantics.toComplex_eq_denote, hlevels,
    LevelSemantics.denote_cons]
  apply Finset.sum_congr rfl
  intro i hi
  have hiDegree : i < level.degree := Finset.mem_range.mp hi
  rw [coeff_toPolynomial]
  have hcoeff : (blockPoly T level b).coeff i =
      T.ofCoeffs (Arithmetic.block (coeffs b) i T.dim) := by
    simp [blockPoly, DensePoly.coeff_ofCoeffs, Array.getD, hiDegree]
  rw [hcoeff, LevelSemantics.toComplex_eq_denote, coeffs_ofCoeffs]
  change LevelSemantics.denote T.levels.toList
      (Arithmetic.fixedCoeffs (levelsDim T.levels.toList)
        (Arithmetic.block (coeffs b) i (levelsDim T.levels.toList))) * _ = _
  rw [LevelSemantics.denote_fixed]

/-- Every returned adjoining payload satisfies the fixed-embedding,
generation, and identity-extension contracts. -/
theorem adjoin?_sound (T : NumberTower) (candidate : AlgebraicRoot)
    {E : Extension T} (h : T.adjoin? candidate = some E) :
    E.Sound candidate := by
  unfold adjoin? at h
  obtain ⟨factorization, hfactorization, h⟩ :=
    Option.bind_eq_some_iff.mp h
  obtain ⟨selected, hselected, h⟩ := Option.bind_eq_some_iff.mp h
  have hfactorizationSound := factor?_sound T
    (liftZPoly T candidate.p) hfactorization
  simp only [Factorization.Sound] at hfactorizationSound
  obtain ⟨entry, hentry, hentrySelected, hentryMultiplicity, hvanish⟩ :=
    selectFactor?_source T candidate factorization.factors hselected
  have hentrySound := hfactorizationSound.2.1 entry hentry
  have hselectedLeading : selected.leadingCoeff = 1 := by
    rw [← hentrySelected]
    exact hentrySound.1
  have hselectedMeaning : PolynomialIrreducible T selected := by
    rw [← hentrySelected]
    exact hentrySound.2.2
  have hselectedVanish :
      Polynomial.eval candidate.toComplex (T.toPolynomial selected) = 0 := by
    rw [← hentrySelected, toPolynomial_eq_polynomial]
    exact (rawVanishesAt_sound T.levels.toList
      (entry.1.toArray.map coeffs) candidate hvanish).mp rfl
  by_cases hdegreeZero : selected.degree?.getD 0 = 0
  · simp [hdegreeZero] at h
  by_cases hdegreeOne : selected.degree?.getD 0 = 1
  · simp only [hdegreeOne, one_ne_zero, ↓reduceIte,
      Option.some.injEq] at h
    subst E
    have hselectedSize : selected.size = 2 := by
      have hsizePos : 0 < selected.size := by
        by_contra hnot
        have hsizeZero : selected.size = 0 := Nat.eq_zero_of_not_pos hnot
        have hnone := DensePoly.degree?_eq_none_iff selected |>.mpr hsizeZero
        rw [hnone] at hdegreeOne
        simp at hdegreeOne
      rw [DensePoly.degree?_eq_some_of_pos_size selected hsizePos,
        Option.getD_some] at hdegreeOne
      omega
    have hcoeffOne : selected.coeff 1 = selected.leadingCoeff := by
      rw [DensePoly.leadingCoeff_eq_coeff_last selected (by omega),
        hselectedSize]
    have hshape : T.toPolynomial selected =
        Polynomial.X + Polynomial.C (T.toComplex (selected.coeff 0)) := by
      have hmonic : (T.toPolynomial selected).Monic := by
        rw [Polynomial.Monic.def, Polynomial.leadingCoeff,
          natDegree_toPolynomial, hdegreeOne, coeff_toPolynomial,
          hcoeffOne, hselectedLeading, map_one]
      simpa only [coeff_toPolynomial] using
        hmonic.eq_X_add_C (by simpa using hdegreeOne)
    have hgenerator :
        T.toComplex (-selected.coeff 0 / selected.leadingCoeff) =
          candidate.toComplex := by
      rw [map_div, map_neg, hselectedLeading, map_one, div_one]
      rw [hshape, Polynomial.eval_add, Polynomial.eval_X,
        Polynomial.eval_C] at hselectedVanish
      exact (eq_neg_of_add_eq_zero_left hselectedVanish).symm
    refine ⟨?_, hgenerator, rfl, ?_, ?_⟩
    · intro a
      rfl
    · intro b
      refine ⟨DensePoly.C b, ?_⟩
      by_cases hb : b = 0
      · subst b
        unfold Extension.evalPoly DensePoly.toArray
        rw [DensePoly.coeffs_C_zero]
        rfl
      · have harray : (DensePoly.C b).toArray = #[b] := by
          exact DensePoly.coeffs_C_of_ne_zero hb
        simp [Extension.evalPoly, harray]
    · constructor
      · intro _
        exact ⟨-selected.coeff 0 / selected.leadingCoeff, hgenerator⟩
      · intro _
        rfl
  · simp only [hdegreeZero, hdegreeOne, ↓reduceIte] at h
    obtain ⟨tower, htower, h⟩ := Option.bind_eq_some_iff.mp h
    simp only [Option.some.injEq] at h
    subst E
    have hdegree : 1 < selected.degree?.getD 0 := by omega
    have hlevelDegree : 1 < (levelOfFactor candidate selected).degree := by
      simpa [levelOfFactor] using hdegree
    have hpreserves := extend_preserves T tower
      (levelOfFactor candidate selected) htower
    have hgenerator := extend_generator T tower
      (levelOfFactor candidate selected) htower hlevelDegree
    refine ⟨hpreserves, hgenerator, rfl, ?_, ?_⟩
    · intro b
      let f := blockPoly T (levelOfFactor candidate selected) b
      refine ⟨f, ?_⟩
      apply toComplex_injective tower
      rw [Extension.toComplex_evalPoly
        ({ tower := tower
           embed := fun a => tower.ofCoeffs (coeffs a)
           gen := tower.ofCoeffs ((Array.replicate T.dim 0).push 1)
           root := candidate } : Extension T) hpreserves hgenerator]
      exact eval_blockPoly T tower (levelOfFactor candidate selected)
        htower (by omega) b
    · have hdimNe : tower.dim ≠ T.dim := by
        rw [Internal.extend?_dim T (levelOfFactor candidate selected) htower]
        change selected.degree?.getD 0 * T.dim ≠ T.dim
        apply Nat.ne_of_gt
        simpa using Nat.mul_lt_mul_of_pos_right hdegree (dim_pos T)
      have hnotContains : ¬ Extension.AlreadyContains T candidate := by
        rintro ⟨a, ha⟩
        have hroot :
            (HexPolyMathlib.toPolynomial selected).eval a = 0 := by
          apply toComplex_injective T
          rw [map_zero T]
          change T.embedding
              ((HexPolyMathlib.toPolynomial selected).eval a) = 0
          rw [← Polynomial.eval_map_apply]
          rw [← toPolynomial_eq_map]
          change Polynomial.eval (T.toComplex a)
              (T.toPolynomial selected) = 0
          rw [ha]
          exact hselectedVanish
        have hirreducible := hselectedMeaning.toMathlib
        have hdegreeNe :
            (HexPolyMathlib.toPolynomial selected).natDegree ≠ 1 := by
          rw [HexPolyMathlib.natDegree_toPolynomial]
          omega
        exact hirreducible.not_isRoot_of_natDegree_ne_one hdegreeNe hroot
      exact ⟨fun hdim => (hdimNe hdim).elim,
        fun hcontains => (hnotContains hcontains).elim⟩

/-- Factor selection and evaluation disambiguation always produce the checked
extension containing the requested algebraic root. -/
theorem adjoin?_isSome (T : NumberTower) (candidate : AlgebraicRoot) :
    (T.adjoin? candidate).isSome := by
  obtain ⟨factorization, hfactorization⟩ := Option.isSome_iff_exists.mp
    (factor?_isSome T (liftZPoly T candidate.p))
  have hsound := factor?_sound T (liftZPoly T candidate.p)
    hfactorization
  have hseparable := liftZPoly_separable T candidate
  obtain ⟨chosen, hchosen, hzero⟩ :=
    exists_vanishing_factor T candidate factorization hsound
  have hmult : ∀ entry ∈ factorization.factors.toList,
      entry.2 = 1 := by
    intro entry hentry
    exact factor_multiplicity_one factorization hsound hseparable
      entry hentry
  have hnodup : factorization.factors.toList.Nodup := by
    apply (factor_fsts_pairwise factorization hsound).imp
    intro a b hfst hab
    exact hfst (congrArg Prod.fst hab)
  have htrue : Evaluation.vanishesAt? T chosen.1 candidate =
      some true :=
    (Evaluation.vanishesAt?_eq_some_true_iff
      T chosen.1 candidate).mpr hzero
  have hfalse : ∀ entry ∈ factorization.factors.toList,
      entry ≠ chosen →
      Evaluation.vanishesAt? T entry.1 candidate = some false := by
    intro entry hentry hne
    obtain ⟨keep, hkeep⟩ := Option.isSome_iff_exists.mp
      (Evaluation.vanishesAt?_isSome T entry.1 candidate)
    cases keep with
    | false => exact hkeep
    | true =>
        have hentryZero :=
          (Evaluation.vanishesAt?_eq_some_true_iff
            T entry.1 candidate).mp hkeep
        exact (hne (vanishing_factor_unique factorization hsound candidate
          entry chosen hentry hchosen hentryZero hzero)).elim
  have hselected := selectFactor?_complete T candidate
    factorization.factors chosen hnodup hchosen hmult htrue hfalse
  have hchosenSound := hsound.2.1 chosen hchosen
  have hchosenIrreducible :
      Irreducible (HexPolyMathlib.toPolynomial chosen.1) :=
    (polynomialIrreducible_iff T chosen.1).mp hchosenSound.2.2
  have hdegree : 0 < chosen.1.degree?.getD 0 := by
    rw [← HexPolyMathlib.natDegree_toPolynomial]
    exact hchosenIrreducible.natDegree_pos
  by_cases hdegreeOne : chosen.1.degree?.getD 0 = 1
  · unfold adjoin?
    simp [hfactorization, hselected, Nat.ne_of_gt hdegree, hdegreeOne]
  · have hdegreeGt : 1 < chosen.1.degree?.getD 0 := by omega
    obtain ⟨tower, htower⟩ := Option.isSome_iff_exists.mp
      (extend_factor_isSome T candidate chosen.1 hchosenSound.1
        hchosenSound.2.2 hzero hdegreeGt)
    unfold adjoin?
    simp [hfactorization, hselected, Nat.ne_of_gt hdegree,
      hdegreeOne, htower]

end Hex.NumberTower
